
<div class="stElementContainer element-container st-key-FormSubmitter-auth_form-Sign-in st-emotion-cache-1u6s8ye e6rk8up1" data-testid="stElementContainer" data-stale="false" width="410"><div class="st-emotion-cache-k008qs e1ttwmlf0" style="width: 410px;"><div class="stFormSubmitButton" data-testid="stFormSubmitButton" style="width: 410px;"><button kind="secondaryFormSubmit" data-testid="stBaseButton-secondaryFormSubmit" aria-label="" class="st-emotion-cache-ocsh0s e1d5ycv58"><div data-testid="stMarkdownContainer" class="st-emotion-cache-1hyd1ho egexzqm0"><p>Sign in</p></div></button></div></div></div>

<label data-testid="stWidgetLabel" aria-hidden="true" for="text_input_1" class="st-emotion-cache-ue6h4q e1dx5vew0"><div data-testid="stMarkdownContainer" class="st-emotion-cache-89jlt8 egexzqm0"><p>Enter password</p></div></label>

<label data-testid="stWidgetLabel" aria-hidden="true" for="text_input_4" class="st-emotion-cache-ue6h4q e1dx5vew0"><div data-testid="stMarkdownContainer" class="st-emotion-cache-89jlt8 egexzqm0"><p>20-character ID to validate</p></div></label>

<div class="stElementContainer element-container st-emotion-cache-a918un e6rk8up1" data-testid="stElementContainer" data-stale="false" width="442"><div class="stButton" data-testid="stButton" style="width: 442px;"><button kind="secondary" data-testid="stBaseButton-secondary" aria-label="" class="st-emotion-cache-ocsh0s e1d5ycv52"><div data-testid="stMarkdownContainer" class="st-emotion-cache-1hyd1ho egexzqm0"><p>Validate</p></div></button></div></div>

<div class="stElementContainer element-container st-emotion-cache-a918un e6rk8up1" data-testid="stElementContainer" data-stale="false" width="442"><div class="stAlert" data-testid="stAlert"><div role="alert" data-baseweb="notification" data-testid="stAlertContainer" class="stAlertContainer st-ax st-ay st-az st-b0 st-b1 st-b2 st-cc st-ef st-ce st-ep st-cg st-ch st-ci st-cj st-ck st-cl st-eg st-at st-av st-aw st-au st-cn st-cw st-cp st-ar st-cq st-af st-cr st-cs st-ct st-cu"><div class="st-ah st-cv"><div data-testid="stAlertContentError" class="st-emotion-cache-wmn9kq en1c6do0"><div class="st-emotion-cache-lk79b8 e17y69s80"><div data-testid="stMarkdownContainer" class="st-emotion-cache-1104ytp egexzqm0" style="width: 100%;"><p>Invalid ID ❌</p></div></div></div></div></div></div></div>